const DATABASE_URL = process.env.REACT_APP_DATABASE_URL;
const MANAGER_URL = process.env.REACT_APP_MANAGER_URL;
const TRAINER_URL = process.env.REACT_APP_TRAINER_URL;
const LEARNER_URL = process.env.REACT_APP_LEARNER_URL;
const TCMAPPING_URL = process.env.REACT_APP_TCMAPPING_URL;
const COURSE_URL = process.env.REACT_APP_COURSE_URL;
const ADMIN_USERNAME = "admin";
const ADMIN_PASSWORD = "admin123";
const TRAINER_USERNAME = "trainer";
const TRAINER_PASSWORD = "trainer123";
const LEARNER_USERNAME = "learner";
const LEARNER_PASSWORD = "learner123";

export {
    DATABASE_URL, MANAGER_URL, TRAINER_URL, LEARNER_URL, TCMAPPING_URL, COURSE_URL, ADMIN_USERNAME, ADMIN_PASSWORD, 
    TRAINER_USERNAME, TRAINER_PASSWORD, LEARNER_USERNAME, LEARNER_PASSWORD
};