const DATABASE_URL = process.env.REACT_APP_DATABASE_URL;
const MANAGER_URL = process.env.REACT_APP_MANAGER_URL;
const TRAINER_URL = process.env.REACT_APP_TRAINER_URL;
const LEARNER_URL = process.env.REACT_APP_LEARNER_URL;
const TCMAPPING_URL = process.env.REACT_APP_TCMAPPING_URL;
const COURSE_URL = process.env.REACT_APP_COURSE_URL;

export {
    DATABASE_URL, MANAGER_URL, TRAINER_URL, LEARNER_URL, TCMAPPING_URL, COURSE_URL
};